version: '3'
services:
  web:
    restart: always
    build: ./nowshare
    ports: ['80:5000']
    volumes: ['./nowshare/app:/code']
  
  db:
    image: alanfluo/cmsc414-hw2-db
    # image: anmazz/mysql-test
    ports: ['32000:3306']

  echo-server:
      image: ealen/echo-server:latest
      environment:
        - ENABLE__ENVIRONMENT=false
        - ENABLE__HOST=true
        - ENABLE__HTTP=false
        - ENABLE__REQUEST=false
        - ENABLE__HEADER=false
        - ENABLE__FILE=false
      ports:
        - 3000:80